package Classes;

public enum RequestsForStudents {
	
	APP_ACADEMIC_MOBILITY,
	BYPASS_SHEET,
	ONAY_RESTORATION,
	MILITARY_COMMITTEE,
	TRANSCRIPT_FOR_ALL,
	TRANSCRIPT_FOR_YEAR, 
	TRANSCRIPT_FOR_SEMESTER
	
}
